# docker-compose.yml
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
    volumes:
      - .:/app
    command: npm run dev
